id: A6077F0FE
base_file: f6A1F.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:24:43.177364
  last_modified_at: 2022-06-19 17:24:43.177372
