id: A6077F0FE
base_file: fB953.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:24:43.181046
  last_modified_at: 2022-06-19 17:24:43.181051
