id: A6077F0FE
base_file: fF2A6.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:24:43.184998
  last_modified_at: 2022-06-19 17:24:43.185002
