id: A6077F0FE
base_file: fEFE5.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:24:43.183419
  last_modified_at: 2022-06-19 17:24:43.183425
